// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: proto/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type MessageType int32

const (
	MessageType_MESSAGE_UNKNOWN      MessageType = 0
	MessageType_MESSAGE_CONNECT      MessageType = 1 // 客户端连接
	MessageType_MESSAGE_FRAME_DATA   MessageType = 2 // 帧数据（上下左右）
	MessageType_MESSAGE_SERVER_FRAME MessageType = 3 // 服务器帧同步数据
	MessageType_MESSAGE_DISCONNECT   MessageType = 4 // 断开连接
	MessageType_MESSAGE_GAME_START   MessageType = 5 // 游戏开始
	MessageType_MESSAGE_FRAME_LOSS   MessageType = 6 // 缺失帧
	MessageType_MESSAGE_FRAME_NEED   MessageType = 7 // 补发帧
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_UNKNOWN",
		1: "MESSAGE_CONNECT",
		2: "MESSAGE_FRAME_DATA",
		3: "MESSAGE_SERVER_FRAME",
		4: "MESSAGE_DISCONNECT",
		5: "MESSAGE_GAME_START",
		6: "MESSAGE_FRAME_LOSS",
		7: "MESSAGE_FRAME_NEED",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_UNKNOWN":      0,
		"MESSAGE_CONNECT":      1,
		"MESSAGE_FRAME_DATA":   2,
		"MESSAGE_SERVER_FRAME": 3,
		"MESSAGE_DISCONNECT":   4,
		"MESSAGE_GAME_START":   5,
		"MESSAGE_FRAME_LOSS":   6,
		"MESSAGE_FRAME_NEED":   7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_game_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

// 输入方向
type InputDirection int32

const (
	InputDirection_DIRECTION_NONE  InputDirection = 0
	InputDirection_DIRECTION_UP    InputDirection = 1
	InputDirection_DIRECTION_DOWN  InputDirection = 2
	InputDirection_DIRECTION_LEFT  InputDirection = 3
	InputDirection_DIRECTION_RIGHT InputDirection = 4
)

// Enum value maps for InputDirection.
var (
	InputDirection_name = map[int32]string{
		0: "DIRECTION_NONE",
		1: "DIRECTION_UP",
		2: "DIRECTION_DOWN",
		3: "DIRECTION_LEFT",
		4: "DIRECTION_RIGHT",
	}
	InputDirection_value = map[string]int32{
		"DIRECTION_NONE":  0,
		"DIRECTION_UP":    1,
		"DIRECTION_DOWN":  2,
		"DIRECTION_LEFT":  3,
		"DIRECTION_RIGHT": 4,
	}
)

func (x InputDirection) Enum() *InputDirection {
	p := new(InputDirection)
	*p = x
	return p
}

func (x InputDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_proto_enumTypes[1].Descriptor()
}

func (InputDirection) Type() protoreflect.EnumType {
	return &file_proto_game_proto_enumTypes[1]
}

func (x InputDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InputDirection.Descriptor instead.
func (InputDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

// 客户端帧数据（只包含上下左右）
type FrameData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`             // 玩家ID
	Direction     InputDirection         `protobuf:"varint,2,opt,name=direction,proto3,enum=proto.InputDirection" json:"direction,omitempty"` // 方向
	FrameNumber   int64                  `protobuf:"varint,3,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`    // 帧号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameData) Reset() {
	*x = FrameData{}
	mi := &file_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameData.ProtoReflect.Descriptor instead.
func (*FrameData) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *FrameData) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *FrameData) GetDirection() InputDirection {
	if x != nil {
		return x.Direction
	}
	return InputDirection_DIRECTION_NONE
}

func (x *FrameData) GetFrameNumber() int64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

// 服务器帧同步数据
type ServerFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameNumber   int64                  `protobuf:"varint,1,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"` // 帧号
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                        // 时间戳
	FrameDatas    []*FrameData           `protobuf:"bytes,3,rep,name=frame_datas,json=frameDatas,proto3" json:"frame_datas,omitempty"`     // 所有玩家的帧数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetFrameNumber() int64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *ServerFrame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ServerFrame) GetFrameDatas() []*FrameData {
	if x != nil {
		return x.FrameDatas
	}
	return nil
}

// 连接消息
type ConnectMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectMessage) Reset() {
	*x = ConnectMessage{}
	mi := &file_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectMessage) ProtoMessage() {}

func (x *ConnectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectMessage.ProtoReflect.Descriptor instead.
func (*ConnectMessage) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectMessage) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ConnectMessage) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// 断开连接消息
type DisconnectMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectMessage) Reset() {
	*x = DisconnectMessage{}
	mi := &file_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectMessage) ProtoMessage() {}

func (x *DisconnectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectMessage.ProtoReflect.Descriptor instead.
func (*DisconnectMessage) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectMessage) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 游戏开始消息
type GameStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                  // 房间ID
	RandomSeed    int64                  `protobuf:"varint,2,opt,name=random_seed,json=randomSeed,proto3" json:"random_seed,omitempty"`     // 随机种子
	PlayerIds     []int32                `protobuf:"varint,3,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"` // 玩家ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStart) Reset() {
	*x = GameStart{}
	mi := &file_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStart) ProtoMessage() {}

func (x *GameStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStart.ProtoReflect.Descriptor instead.
func (*GameStart) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameStart) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameStart) GetRandomSeed() int64 {
	if x != nil {
		return x.RandomSeed
	}
	return 0
}

func (x *GameStart) GetPlayerIds() []int32 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

type GetLossFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LastFrameNumber int64                  `protobuf:"varint,1,opt,name=last_frame_number,json=lastFrameNumber,proto3" json:"last_frame_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLossFrame) Reset() {
	*x = GetLossFrame{}
	mi := &file_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLossFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLossFrame) ProtoMessage() {}

func (x *GetLossFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLossFrame.ProtoReflect.Descriptor instead.
func (*GetLossFrame) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *GetLossFrame) GetLastFrameNumber() int64 {
	if x != nil {
		return x.LastFrameNumber
	}
	return 0
}

type SendAllFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllNeedFrame  []*ServerFrame         `protobuf:"bytes,1,rep,name=all_need_frame,json=allNeedFrame,proto3" json:"all_need_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAllFrame) Reset() {
	*x = SendAllFrame{}
	mi := &file_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAllFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAllFrame) ProtoMessage() {}

func (x *SendAllFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAllFrame.ProtoReflect.Descriptor instead.
func (*SendAllFrame) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *SendAllFrame) GetAllNeedFrame() []*ServerFrame {
	if x != nil {
		return x.AllNeedFrame
	}
	return nil
}

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\x05proto\"\x80\x01\n" +
	"\tFrameData\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x123\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x15.proto.InputDirectionR\tdirection\x12!\n" +
	"\fframe_number\x18\x03 \x01(\x03R\vframeNumber\"\x81\x01\n" +
	"\vServerFrame\x12!\n" +
	"\fframe_number\x18\x01 \x01(\x03R\vframeNumber\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x121\n" +
	"\vframe_datas\x18\x03 \x03(\v2\x10.proto.FrameDataR\n" +
	"frameDatas\"N\n" +
	"\x0eConnectMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"0\n" +
	"\x11DisconnectMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\"d\n" +
	"\tGameStart\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vrandom_seed\x18\x02 \x01(\x03R\n" +
	"randomSeed\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x03 \x03(\x05R\tplayerIds\":\n" +
	"\fGetLossFrame\x12*\n" +
	"\x11last_frame_number\x18\x01 \x01(\x03R\x0flastFrameNumber\"H\n" +
	"\fSendAllFrame\x128\n" +
	"\x0eall_need_frame\x18\x01 \x03(\v2\x12.proto.ServerFrameR\fallNeedFrame*\xc9\x01\n" +
	"\vMessageType\x12\x13\n" +
	"\x0fMESSAGE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fMESSAGE_CONNECT\x10\x01\x12\x16\n" +
	"\x12MESSAGE_FRAME_DATA\x10\x02\x12\x18\n" +
	"\x14MESSAGE_SERVER_FRAME\x10\x03\x12\x16\n" +
	"\x12MESSAGE_DISCONNECT\x10\x04\x12\x16\n" +
	"\x12MESSAGE_GAME_START\x10\x05\x12\x16\n" +
	"\x12MESSAGE_FRAME_LOSS\x10\x06\x12\x16\n" +
	"\x12MESSAGE_FRAME_NEED\x10\a*s\n" +
	"\x0eInputDirection\x12\x12\n" +
	"\x0eDIRECTION_NONE\x10\x00\x12\x10\n" +
	"\fDIRECTION_UP\x10\x01\x12\x12\n" +
	"\x0eDIRECTION_DOWN\x10\x02\x12\x12\n" +
	"\x0eDIRECTION_LEFT\x10\x03\x12\x13\n" +
	"\x0fDIRECTION_RIGHT\x10\x04B\"Z github.com/WjcHome/gohello/protob\x06proto3"

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData []byte
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)))
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_game_proto_goTypes = []any{
	(MessageType)(0),          // 0: proto.MessageType
	(InputDirection)(0),       // 1: proto.InputDirection
	(*FrameData)(nil),         // 2: proto.FrameData
	(*ServerFrame)(nil),       // 3: proto.ServerFrame
	(*ConnectMessage)(nil),    // 4: proto.ConnectMessage
	(*DisconnectMessage)(nil), // 5: proto.DisconnectMessage
	(*GameStart)(nil),         // 6: proto.GameStart
	(*GetLossFrame)(nil),      // 7: proto.GetLossFrame
	(*SendAllFrame)(nil),      // 8: proto.SendAllFrame
}
var file_proto_game_proto_depIdxs = []int32{
	1, // 0: proto.FrameData.direction:type_name -> proto.InputDirection
	2, // 1: proto.ServerFrame.frame_datas:type_name -> proto.FrameData
	3, // 2: proto.SendAllFrame.all_need_frame:type_name -> proto.ServerFrame
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		EnumInfos:         file_proto_game_proto_enumTypes,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
